---
- name: add group {{manager_group}}
  group:
    name: "{{manager_group}}"
    state: present

- name: add user {{manager_user}}
  user:
    name: "{{manager_user}}"
    group: "{{manager_group}}"
    state: present

- name: create jms APP_DIR directory
  file:
    path: "{{jms.APP_DIR}}"
    owner: "{{manager_user}}"
    group: "{{manager_group}}"
    state: directory
    recurse: yes
    mode: 0755

- name: stop selinux status
  shell:
    setenforce 0
  ignore_errors: yes

- name: disable selinux
  selinux:
    state: disabled

- name: disable firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: True

- name: install basic progrems
  yum:
    name: "{{item}}"
    state: present
  with_items:
    - wget
    - sqlite-devel
    - xz
    - gcc
    - automake
    - zlib-devel
    - openssl-devel
    - epel-release
    - git


#设置系统的socket连接的处理限制
- name: tune kernal parameters
  sysctl:
    name: net.core.somaxconn
    value: 2048
    state: present
