---
- name: stop guacamole service
  shell: |
    ps -ef |grep {{item}} |grep -v grep |awk '{print $2}'|xargs kill -9
  with_items:
    - guacd
    - 'guacamole/tomcat'
  ignore_errors: true


- name: clearn guacamole files
  file:
    path: "{{item}}"
    state: absent
  with_items:
     - /usr/local/lib/freerdp/
     - /usr/lib64/freerdp/freerdp
     - /tmp/docker-guacamole-master
     - /tmp/docker-guacamole-master.zip
     - "{{jms.APP_DIR}}/guacamole"


- name: create freerdop directory
  shell: |
     mkdir /usr/local/lib/freerdp/
     ln -s /usr/local/lib/freerdp /usr/lib64/freerdp

- name: update repository
  shell: |
     rpm --import 'http://li.nux.ro/download/nux/RPM-GPG-KEY-nux.ro'
     rpm -Uvh http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
     yum -y localinstall --nogpgcheck https://download1.rpmfusion.org/free/el/rpmfusion-free-release-7.noarch.rpm https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-7.noarch.rpm


- name: install base package
  yum:
    name: "{{item}}"
    state: present
  with_items:
      - java-1.8.0-openjdk 
      - libtool
      - cairo-devel 
      - libjpeg-turbo-devel 
      - libpng-devel 
      - uuid-devel
      - ffmpeg-devel 
      - freerdp-devel 
      - freerdp-plugins 
      - pango-devel 
      - libssh2-devel 
      - libtelnet-devel 
      - libvncserver-devel 
      - pulseaudio-libs-devel 
      - openssl-devel 
      - libvorbis-devel 
      - libwebp-devel 
      - ghostscript


- name: download docker-guacamole
  get_url:
    url:  "{{guacamole_repo}}"
    dest: /tmp/
    mode: 0755

- name: unarchive docker-guacamole package
  unarchive:
    src: /tmp/docker-guacamole-master.zip
    dest: /tmp/
    remote_src: yes
    mode: 0755


- name: get guacamole-server version
  shell: |
    version=`echo * |xargs -n 1|grep guacamole-server|grep 'tar.gz'`
    echo ${version%.tar*}
  args:
    chdir: /tmp/docker-guacamole-master/
  register: guacamole_server_version


- name: unarchive guacamole-server package
  unarchive:
      src: "/tmp/docker-guacamole-master/{{guacamole_server_version.stdout}}.tar.gz"
      dest: /tmp/docker-guacamole-master/
      mode: 0755
      remote_src: yes


- name: create guacamole config directory
  file:
    path: "{{item}}"
    state: directory
  with_items:
     - "{{jms.APP_DIR}}/guacamole"
     - "{{jms.APP_DIR}}/guacamole/lib"
     - "{{jms.APP_DIR}}/guacamole/extensions"


- name: compile guacamole-server
  shell: |
    autoreconf -fi ;
    ./configure --with-init-dir="{{jms.APP_DIR}}/guacamole";
    make && make install
  args:
    chdir: "/tmp/docker-guacamole-master/{{guacamole_server_version.stdout}}"


- name: update guacamole_server config
  shell: |
    ldconfig
  args:
    chdir: "{{jms.APP_DIR}}/guacamole/"



- name: get guacamole-auth-jumpserver jar version
  shell: |
    echo * |xargs -n 1|grep guacamole-auth-jumpserver
  args:
    chdir: /tmp/docker-guacamole-master/
  register: guacamole_auth_jumpserver_version

- name: copy guacamole-auth-jumpserver
  copy:
    src: "/tmp/docker-guacamole-master/{{guacamole_auth_jumpserver_version.stdout}}"
    dest: "{{jms.APP_DIR}}/guacamole/extensions/{{guacamole_auth_jumpserver_version.stdout}}"
    remote_src: yes


- name: copy guacamole.properties
  copy:
    src: "/tmp/docker-guacamole-master/root/app/guacamole/guacamole.properties"
    dest: "{{jms.APP_DIR}}/guacamole/guacamole.properties"
    remote_src: yes



- name: download tomcat
  get_url:
    url:  "{{guacamole_tomcat_url}}"
    dest: "{{jms.APP_DIR}}/guacamole"
    mode: 0755


- name: get guacamole-tomcat version
  shell: |
    version=`echo * |xargs -n 1|grep apache-tomcat`;
    echo ${version%.tar*}
  args:
    chdir: "{{jms.APP_DIR}}/guacamole"
  register: guacamole_tomcat_version

- name: unarchive guacamole-tomcat
  unarchive:
    src: "{{jms.APP_DIR}}/guacamole/{{guacamole_tomcat_version.stdout}}.tar.gz"
    dest: "{{jms.APP_DIR}}/guacamole/"
    remote_src: yes
    mode: 0755

- name: rename guacamole-tomcat
  shell: |
     mv {{guacamole_tomcat_version.stdout}}  tomcat
  args:
    chdir: "{{jms.APP_DIR}}/guacamole/"


- name: get guacamole war version
  shell: |
    echo * |xargs -n 1|grep guacamole |grep war
  args:
    chdir: /tmp/docker-guacamole-master/
  register: guacamole_war_version


- name: config guacamole-tomcat webapp
  shell: |
    rm -rf {{jms.APP_DIR}}/guacamole/tomcat/webapps/*;
    cp /tmp/docker-guacamole-master/{{guacamole_war_version.stdout}}  {{jms.APP_DIR}}/guacamole/tomcat/webapps/ROOT.war;
    sed -i 's/Connector port="8080"/Connector port="{{guacamole.HTTP_LISTEN_PORT}}"/g' `grep 'Connector port="8080"' -rl  {{jms.APP_DIR}}/guacamole/tomcat/conf/server.xml`;
    sed -i 's/FINE/WARNING/g' `grep 'FINE' -rl  {{jms.APP_DIR}}/guacamole/tomcat/conf/logging.properties` 


- name: clearn ssh-forward package
  file:
    path: "{{item}}"
    state: absent
  with_items:
      - /tmp/linux-amd64.tar.gz
      - /tmp/ssh-forward/

- name: create ssh-forward directory
  file: 
    path: /tmp/ssh-forward
    state: directory

- name: git clone ssh-forward 
  git:
    repo:  "{{guacamole_ssh_forward_repo}}"
    dest: /tmp/ssh-forward


- name: get ssh-forward release version
  shell: |
    git tag |grep 'v'
  args:
    chdir: /tmp/ssh-forward/
  register: ssh_forward_version

- name: download ssh-forward package
  get_url:
    url:  "https://github.com/ibuler/ssh-forward/releases/download/{{ssh_forward_version.stdout_lines[-1]}}/linux-amd64.tar.gz"
    dest: /tmp/
    mode: 0755


- name: unarchive ssh-forward package
  unarchive:
    src: /tmp/linux-amd64.tar.gz
    dest: /bin/
    mode: 0755
    remote_src: yes


- name: create  BOOTSTRAP_TOKEN
  shell:
    echo {{ansible_machine_id}}
  register: bootstrap_token 
  connection: local


- name: config guacamole environment 
  blockinfile:
    path: "{{jms.APP_DIR}}/guacamole/profile"
    create: yes
    marker: "# {mark} ANSIBLE guacamole environment BLOCK "
    block: |
       export JUMPSERVER_SERVER=http://{{jms.HOST}}:{{jms.HTTP_LISTEN_PORT}}
       export BOOTSTRAP_TOKEN={{bootstrap_token.stdout}}
       export JUMPSERVER_KEY_DIR={{jms.APP_DIR}}/guacamole/keys
       export GUACAMOLE_HOME={{jms.APP_DIR}}/guacamole


- name: chown guacamole directory
  file:
    path: "{{item}}"
    owner: "{{manager_user}}"
    group: "{{manager_group}}"
    recurse: yes
    mode: 0755
  with_items:
      - "{{jms.APP_DIR}}/guacamole"


- name: start guacamole services(root)
  shell: | 
    source {{jms.APP_DIR}}/guacamole/profile;{{jms.APP_DIR}}/guacamole/guacd start;
    source {{jms.APP_DIR}}/guacamole/profile;set -m;sh {{jms.APP_DIR}}/guacamole/tomcat/bin/startup.sh


    
- name: copy guacamole start/stop scripts
  template:
    src: "{{item}}"
    dest: "{{jms.APP_DIR}}/guacamole/"
    mode: 0755
  with_items:
    - guacamole_start.sh
    - guacamole_stop.sh
