- hosts: all
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - prepare
    - python
    - mariadb
    - redis
    - backup_jms
    - jumpserver
    - coco
    - guacamole
    - luna
    - nginx
